### ISSUE TITLE
使用WebDAV连接私人的nextcloud失败

### ISSUE THREAD

**Issue by donomnivora** [Kenshin/simpread#3473]
使用选项页中WebDav连接私人的nextcloud的webdav失败，chrome报错 

Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://ssl.google-analytics.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

webdav地址密码使用其他工具连接成功。应该是chrome安全的问题

**Comment by Kenshin** [comment]
嗨，我看到你关闭了这个 Issues 是搞定了？还是？

**Comment by anschein** [comment]
> 查了下ISSUES感觉相关请求挺少，不重新开ISSUES了先来问问，我也是私有部署的NEXTCLOUD无法连接

开调试模式是同样的报错，tions.html#connect:1 Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' https://ssl.google-analytics.com". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
但是怀疑根这个没关系
