### ISSUE TITLE
能否加入朗读功能？

### ISSUE THREAD

**Issue by Alanomn** [Kenshin/simpread#435]
像Reader View扩展就能，进入简约模式后，按朗读器图标，开始朗诵中文和英文？

**Comment by Kenshin** [comment]
进入阅读模式 → 右侧控制栏 → 动作 → （滚动条拉下一些）无障碍 即可朗读。

**Comment by Alanomn** [comment]
非常感谢开发者的提醒

**Comment by Kenshin** [comment]
搞定就好，没有问题的话，我将关闭这个 issues ~

**Comment by zsedcbm** [comment]
为什么我点击朗读没有效果? 我访问的是知乎, 浏览器是360极速,版本13.0.1088, 查看了一下console,提示内容如下

Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' blob: *.zhihu.com g.alicdn.com qzonestyle.gtimg.cn res.wx.qq.com open.mobile.qq.com 'unsafe-eval' unpkg.zhimg.com unicom.zhimg.com captcha.gtimg.com captcha.guard.qcloud.com pagead2.googlesyndication.com cpro.baidustatic.com pos.baidu.com dup.baidustatic.com i.hao61.net 'nonce-534faad6-6bab-4dae-a7ac-f791c4bac626' hm.baidu.com zz.bdstatic.com www.googletagmanager.com beta-mini-app-static.jd.com resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by Kenshin** [comment]
@zsedcbm 

建议试试其它浏览器，如 Edge 另外，Edge 自带的朗读效果也不错，并且兼容简悦。

**Comment by zsedcbm** [comment]
> @zsedcbm
> 
> 建议试试其它浏览器，如 Edge 另外，Edge 自带的朗读效果也不错，并且兼容简悦。

最新版的edge也不行, 也是提示这个错误, 这个应该是浏览器内核安全方面升级了, 导致插件内部朗读功能无法使用.

edge版本 85.0.564.63 (官方内部版本) (64 位)

![1](https://user-images.githubusercontent.com/5986396/94222684-a0cc4780-ff20-11ea-8b1a-e0ce604879dc.png)

**Comment by Kenshin** [comment]
嗨，我的意思是，你可以试试 **Edge 自带的朗读** 功能。

![image](https://user-images.githubusercontent.com/81074/94223117-bb52f080-ff21-11ea-81f6-6f242c91754e.png)

**Comment by zsedcbm** [comment]
edge这图标有点迷， 有些网页有，有些没有。后来发现右键菜单有，试用了一下，体验还行，就是有时候会卡顿。

插件的这个问题不修复一下吗？

**Comment by Kenshin** [comment]
@zsedcbm 

之前也有用户反映，偶尔会卡（怀疑是 Edge 的问题）

另外，我测试了下 Chrome 是没有这个问题的话，所以请尽量使用干净一些的  Chromium  内核版本。
